### ISSUE TITLE
Wiring 6 rows and wireless module

### ISSUE THREAD

**Issue by Merlin04** [ahtn/keyboard_pcb#1]
How do use a keyplus with a wireless module if the layout has 6 rows?

**Comment by ahtn** [comment]
Just use rows 0 through 5 (that's 6 since counting starts at 0).

If you need more than 6, the `COL15, COL14, COL13, COL12` pins (underlined on the PCB) may also be used
as `ROW` pins. They map to the following row pins:

* ROW6: COL15
* ROW7: COL14
* ROW8: COL13
* ROW9: COL12


It's also possible to use any of the pins as rows/columns by giving a list of pins:
```
    scan_mode:
      mode: col_row
      rows: [D2, D3, D1, D0]
      cols: [A2, A1, A0, A3, A4, A5]
```
If you use this approach, you need to use the pin names for the ATxmega microcontroller. This image shows the pin names which are printed on the PCB and their corresponding names on the micrcontroller:
![pin-names](https://user-images.githubusercontent.com/13606000/38773028-07e69e58-4087-11e8-8ab3-f58f304bc81f.png)
